/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FreshmanTransition;

/**
 *
 * @author jilli
 */
public class Home extends javax.swing.JFrame {

    public static final int xSize = 400;
    public static final int ySize = 400;
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setLocation(800-200, 450 - 200);
        this.setSize(xSize, ySize);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginBlackPanel = new javax.swing.JPanel();
        homeWelcomeTxt = new javax.swing.JLabel();
        homeBackground = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Freshman Transition");
        getContentPane().setLayout(null);

        loginBlackPanel.setBackground(new java.awt.Color(0, 0, 0));
        loginBlackPanel.setForeground(new java.awt.Color(255, 255, 255));

        homeWelcomeTxt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        homeWelcomeTxt.setForeground(new java.awt.Color(255, 255, 255));
        homeWelcomeTxt.setText("Welcome Jillian!");

        javax.swing.GroupLayout loginBlackPanelLayout = new javax.swing.GroupLayout(loginBlackPanel);
        loginBlackPanel.setLayout(loginBlackPanelLayout);
        loginBlackPanelLayout.setHorizontalGroup(
            loginBlackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBlackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeWelcomeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        loginBlackPanelLayout.setVerticalGroup(
            loginBlackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBlackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeWelcomeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(loginBlackPanel);
        loginBlackPanel.setBounds(0, 0, 400, 60);

        homeBackground.setToolTipText("");
        getContentPane().add(homeBackground);
        homeBackground.setBounds(0, 0, 0, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\jilli\\Documents\\GitHub\\FreshmanTransition\\resources\\career button 50x50.jpg")); // NOI18N
        jLabel1.setText("Career Finder");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 80, 130, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\jilli\\Documents\\GitHub\\FreshmanTransition\\resources\\web button 50x50.png")); // NOI18N
        jLabel2.setText("Student Intranet");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 140, 140, 50);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 210, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        // TODO add your handling code here:
        Survey survey = new Survey();
        survey.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseReleased

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        // TODO add your handling code here:
        Hyperlinks hyp = new Hyperlinks();
        hyp.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel homeBackground;
    private javax.swing.JLabel homeWelcomeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel loginBlackPanel;
    // End of variables declaration//GEN-END:variables
}
