/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FreshmanTransition;

/**
 *
 * @author jilli
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocation(800-200, 450 - 200);
        this.setSize(Home.xSize, Home.ySize);
        String firstName = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTxtFld = new javax.swing.JTextField();
        loginBlackPanel = new javax.swing.JPanel();
        loginWelcomeTxt = new javax.swing.JLabel();
        startBtn = new javax.swing.JButton();
        loginBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Freshman Transition");
        getContentPane().setLayout(null);

        nameTxtFld.setForeground(new java.awt.Color(153, 153, 153));
        nameTxtFld.setText("Enter First and Last Name Here");
        nameTxtFld.setToolTipText("");
        getContentPane().add(nameTxtFld);
        nameTxtFld.setBounds(49, 110, 300, 20);

        loginBlackPanel.setBackground(new java.awt.Color(0, 0, 0));
        loginBlackPanel.setForeground(new java.awt.Color(255, 255, 255));

        loginWelcomeTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginWelcomeTxt.setForeground(new java.awt.Color(255, 255, 255));
        loginWelcomeTxt.setText("Welcome to the WTHS Freshmen Transition Program!");
        loginWelcomeTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout loginBlackPanelLayout = new javax.swing.GroupLayout(loginBlackPanel);
        loginBlackPanel.setLayout(loginBlackPanelLayout);
        loginBlackPanelLayout.setHorizontalGroup(
            loginBlackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBlackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginWelcomeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        loginBlackPanelLayout.setVerticalGroup(
            loginBlackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBlackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginWelcomeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(loginBlackPanel);
        loginBlackPanel.setBounds(0, 0, 400, 60);

        startBtn.setText("Start");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });
        getContentPane().add(startBtn);
        startBtn.setBounds(160, 180, 73, 23);
        getContentPane().add(loginBackground);
        loginBackground.setBounds(0, 0, 400, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.setVisible(false);

        String fullName = nameTxtFld.getText();
        int space = fullName.indexOf(" ");
        String firstName = fullName.substring(0, space);

    }//GEN-LAST:event_startBtnActionPerformed

    
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loginBackground;
    private javax.swing.JPanel loginBlackPanel;
    private javax.swing.JLabel loginWelcomeTxt;
    private javax.swing.JTextField nameTxtFld;
    private javax.swing.JButton startBtn;
    // End of variables declaration//GEN-END:variables
}
