/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FreshmanTransition;

/**
 *
 * @author jilli
 */
public class Survey extends javax.swing.JFrame {

    /**
     * Creates new form CareerSurvey
     */
    private int counter;
    private int artCounter;
    private int stemCounter;
    private int lawCounter;
    private int medicalCounter;
    
    public Survey() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setLocation(800-200, 450 - 200);
        this.setSize(Home.xSize, Home.ySize);
        counter = 0;
        artCounter = 0;
        stemCounter = 0;
        lawCounter = 0;
        medicalCounter = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        choiceABtn = new javax.swing.JRadioButton();
        choiceBBtn = new javax.swing.JRadioButton();
        choiceCBtn = new javax.swing.JRadioButton();
        choiceDBtn = new javax.swing.JRadioButton();
        surveyBlackPanel = new javax.swing.JPanel();
        questionTxt = new javax.swing.JLabel();
        surveyBackground = new javax.swing.JLabel();
        nextBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Freshman Transition");
        getContentPane().setLayout(null);

        buttonGroup1.add(choiceABtn);
        choiceABtn.setText("Watch movie or play video games");
        choiceABtn.setName(""); // NOI18N
        getContentPane().add(choiceABtn);
        choiceABtn.setBounds(30, 100, 340, 23);

        buttonGroup1.add(choiceBBtn);
        choiceBBtn.setText("Play video games");
        getContentPane().add(choiceBBtn);
        choiceBBtn.setBounds(30, 130, 340, 23);

        buttonGroup1.add(choiceCBtn);
        choiceCBtn.setText("Talk with friends");
        getContentPane().add(choiceCBtn);
        choiceCBtn.setBounds(30, 160, 340, 23);

        buttonGroup1.add(choiceDBtn);
        choiceDBtn.setText("Exercise");
        getContentPane().add(choiceDBtn);
        choiceDBtn.setBounds(30, 190, 340, 23);

        surveyBlackPanel.setBackground(new java.awt.Color(0, 0, 0));
        surveyBlackPanel.setForeground(new java.awt.Color(255, 255, 255));

        questionTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        questionTxt.setForeground(new java.awt.Color(255, 255, 255));
        questionTxt.setText("What do you like to do in your free time?");

        javax.swing.GroupLayout surveyBlackPanelLayout = new javax.swing.GroupLayout(surveyBlackPanel);
        surveyBlackPanel.setLayout(surveyBlackPanelLayout);
        surveyBlackPanelLayout.setHorizontalGroup(
            surveyBlackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(surveyBlackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        surveyBlackPanelLayout.setVerticalGroup(
            surveyBlackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(surveyBlackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(surveyBlackPanel);
        surveyBlackPanel.setBounds(0, 0, 400, 60);
        getContentPane().add(surveyBackground);
        surveyBackground.setBounds(0, 0, 0, 0);

        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nextBtn);
        nextBtn.setBounds(150, 240, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        counter++;
        if(counter == 5){
            Survey survWin = new Survey();
            this.dispose();
            SurveyResults res = new SurveyResults();
            res.setVisible(true);
        }else{
            switch(counter){
                case 1:
                    questionTxt.setText("What is your favorite subject?");
                    choiceABtn.setText("Art/Music Class");
                    choiceBBtn.setText("Math");
                    choiceCBtn.setText("History");
                    choiceDBtn.setText("Science");
                    break;
                case 2:
                    questionTxt.setText("What do you do like to do best in a group project?");
                    choiceABtn.setText("Make the poster");
                    choiceBBtn.setText("Build the model");
                    choiceCBtn.setText("Present");
                    choiceDBtn.setText("Science");
                    break;
                case 3:
                    questionTxt.setText("You have a project due tomorrow. What do you do?");
                    choiceABtn.setText("Make the most visually attractive project you can");
                    choiceBBtn.setText("Quickly throw together the best project you can");
                    choiceCBtn.setText("Email your teacher about why you can't do your project");
                    choiceDBtn.setText("Do the research for your project and skip the visuals");
                    break;
                case 4:
                    questionTxt.setText("What do you like most at a party?");
                    choiceABtn.setText("Nice decorations and a good theme");
                    choiceBBtn.setText("To play games");
                    choiceCBtn.setText("Talk with friends/family");
                    choiceDBtn.setText("Hands-on activities");
                    nextBtn.setText("Submit");
                    break;
            }
            
        }
        if(buttonGroup1.getSelection() == choiceABtn){
            artCounter++;
        }else if(buttonGroup1.getSelection() == choiceBBtn){
            stemCounter++;
        }else if(buttonGroup1.getSelection() == choiceCBtn){
            lawCounter++;
        }else{
            medicalCounter++;
        }
        
        
    }//GEN-LAST:event_nextBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Survey().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton choiceABtn;
    private javax.swing.JRadioButton choiceBBtn;
    private javax.swing.JRadioButton choiceCBtn;
    private javax.swing.JRadioButton choiceDBtn;
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel questionTxt;
    private javax.swing.JLabel surveyBackground;
    private javax.swing.JPanel surveyBlackPanel;
    // End of variables declaration//GEN-END:variables
}
